-- Update gallery URLs for all aircraft
-- Each aircraft gets 5 images: 01.jpg through 05.jpg

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Airbus%20318%20Elite/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Airbus%20318%20Elite/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Airbus%20318%20Elite/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Airbus%20318%20Elite/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Airbus%20318%20Elite/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Airbus%20318%20Elite/01.jpg' WHERE name = 'Airbus 318 Elite';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20604/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20604/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20604/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20604/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20604/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20604/01.jpg' WHERE name = 'Challenger 604';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20605/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20605/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20605/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20605/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20605/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20605/01.jpg' WHERE name = 'Challenger 605';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20650/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20650/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20650/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20650/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20650/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20650/01.jpg' WHERE name = 'Challenger 650';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20850/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20850/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20850/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20850/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20850/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Challenger%20850/01.jpg' WHERE name = 'Challenger 850';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ/01.jpg' WHERE name = 'Citation CJ';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ1/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ1/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ1/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ1/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ1/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ1/01.jpg' WHERE name = 'Citation CJ1';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ2/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ2/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ2/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ2/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ2/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ2/01.jpg' WHERE name = 'Citation CJ2';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ2%2B/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ2%2B/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ2%2B/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ2%2B/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ2%2B/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ2%2B/01.jpg' WHERE name = 'Citation CJ2+';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ3/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ3/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ3/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ3/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ3/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ3/01.jpg' WHERE name = 'Citation CJ3';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ4/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ4/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ4/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ4/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ4/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20CJ4/01.jpg' WHERE name = 'Citation CJ4';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20II/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20II/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20II/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20II/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20II/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20II/01.jpg' WHERE name = 'Citation II';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20III/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20III/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20III/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20III/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20III/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20III/01.jpg' WHERE name = 'Citation III';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Latitude/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Latitude/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Latitude/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Latitude/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Latitude/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Latitude/01.jpg' WHERE name = 'Citation Latitude';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20M2/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20M2/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20M2/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20M2/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20M2/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20M2/01.jpg' WHERE name = 'Citation M2';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Mustang/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Mustang/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Mustang/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Mustang/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Mustang/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Mustang/01.jpg' WHERE name = 'Citation Mustang';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Sovereign/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Sovereign/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Sovereign/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Sovereign/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Sovereign/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Sovereign/01.jpg' WHERE name = 'Citation Sovereign';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Ultra/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Ultra/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Ultra/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Ultra/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Ultra/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20Ultra/01.jpg' WHERE name = 'Citation Ultra';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20X/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20X/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20X/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20X/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20X/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20X/01.jpg' WHERE name = 'Citation X';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20XLS/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20XLS/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20XLS/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20XLS/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20XLS/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20XLS/01.jpg' WHERE name = 'Citation XLS';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20XLS%2B/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20XLS%2B/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20XLS%2B/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20XLS%2B/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20XLS%2B/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Citation%20XLS%2B/01.jpg' WHERE name = 'Citation XLS+';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20135%20LR/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20135%20LR/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20135%20LR/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20135%20LR/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20135%20LR/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20135%20LR/01.jpg' WHERE name = 'Embraer 135 LR';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20145%20LR/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20145%20LR/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20145%20LR/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20145%20LR/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20145%20LR/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20145%20LR/01.jpg' WHERE name = 'Embraer 145 LR';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20Lineage%201000/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20Lineage%201000/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20Lineage%201000/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20Lineage%201000/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20Lineage%201000/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Embraer%20Lineage%201000/01.jpg' WHERE name = 'Embraer Lineage 1000';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%207X/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%207X/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%207X/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%207X/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%207X/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%207X/01.jpg' WHERE name = 'Falcon 7X';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%208X/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%208X/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%208X/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%208X/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%208X/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%208X/01.jpg' WHERE name = 'Falcon 8X';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%20900/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%20900/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%20900/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%20900/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%20900/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%20900/01.jpg' WHERE name = 'Falcon 900';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000/01.jpg' WHERE name = 'Falcon 2000';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000LXS/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000LXS/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000LXS/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000LXS/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000LXS/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000LXS/01.jpg' WHERE name = 'Falcon 2000LXS';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000S/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000S/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000S/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000S/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000S/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Falcon%202000S/01.jpg' WHERE name = 'Falcon 2000S';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%205000/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%205000/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%205000/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%205000/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%205000/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%205000/01.jpg' WHERE name = 'Global 5000';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%206000/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%206000/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%206000/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%206000/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%206000/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%206000/01.jpg' WHERE name = 'Global 6000';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%206500/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%206500/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%206500/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%206500/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%206500/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%206500/01.jpg' WHERE name = 'Global 6500';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%20Express%20XRS/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%20Express%20XRS/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%20Express%20XRS/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%20Express%20XRS/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%20Express%20XRS/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Global%20Express%20XRS/01.jpg' WHERE name = 'Global Express XRS';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-150/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-150/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-150/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-150/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-150/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-150/01.jpg' WHERE name = 'Gulfstream G-150';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-200/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-200/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-200/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-200/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-200/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-200/01.jpg' WHERE name = 'Gulfstream G-200';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-280/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-280/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-280/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-280/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-280/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-280/01.jpg' WHERE name = 'Gulfstream G-280';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-450/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-450/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-450/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-450/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-450/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-450/01.jpg' WHERE name = 'Gulfstream G-450';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-500/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-500/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-500/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-500/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-500/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-500/01.jpg' WHERE name = 'Gulfstream G-500';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-650/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-650/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-650/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-650/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-650/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-650/01.jpg' WHERE name = 'Gulfstream G-650';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-IV/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-IV/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-IV/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-IV/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-IV/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Gulfstream%20G-IV/01.jpg' WHERE name = 'Gulfstream G-IV';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20700A/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20700A/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20700A/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20700A/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20700A/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20700A/01.jpg' WHERE name = 'Hawker 700A';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20750/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20750/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20750/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20750/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20750/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20750/01.jpg' WHERE name = 'Hawker 750';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20800XP/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20800XP/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20800XP/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20800XP/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20800XP/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20800XP/01.jpg' WHERE name = 'Hawker 800XP';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20900XP/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20900XP/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20900XP/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20900XP/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20900XP/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Hawker%20900XP/01.jpg' WHERE name = 'Hawker 900XP';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/HondaJet/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/HondaJet/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/HondaJet/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/HondaJet/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/HondaJet/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/HondaJet/01.jpg' WHERE name = 'HondaJet';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/KingAir/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/KingAir/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/KingAir/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/KingAir/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/KingAir/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/KingAir/01.jpg' WHERE name = 'King Air';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2031/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2031/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2031/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2031/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2031/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2031/01.jpg' WHERE name = 'Learjet 31';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2031A/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2031A/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2031A/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2031A/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2031A/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2031A/01.jpg' WHERE name = 'Learjet 31A';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2040/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2040/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2040/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2040/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2040/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2040/01.jpg' WHERE name = 'Learjet 40';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2045/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2045/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2045/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2045/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2045/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2045/01.jpg' WHERE name = 'Learjet 45';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2060/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2060/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2060/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2060/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2060/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Learjet%2060/01.jpg' WHERE name = 'Learjet 60';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20450/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20450/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20450/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20450/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20450/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20450/01.jpg' WHERE name = 'Legacy 450';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20500/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20500/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20500/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20500/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20500/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20500/01.jpg' WHERE name = 'Legacy 500';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20600/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20600/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20600/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20600/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20600/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20600/01.jpg' WHERE name = 'Legacy 600';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20650/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20650/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20650/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20650/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20650/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Legacy%20650/01.jpg' WHERE name = 'Legacy 650';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Phenom%20300/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Phenom%20300/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Phenom%20300/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Phenom%20300/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Phenom%20300/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Phenom%20300/01.jpg' WHERE name = 'Phenom 300';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Phenom100/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Phenom100/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Phenom100/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Phenom100/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Phenom100/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Phenom100/01.jpg' WHERE name = 'Phenom 100';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Piaggo%20Avanti/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Piaggo%20Avanti/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Piaggo%20Avanti/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Piaggo%20Avanti/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Piaggo%20Avanti/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Piaggo%20Avanti/01.jpg' WHERE name = 'Piaggio Avanti';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Pilatus%20PC-12%2F47E%20(NG)/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Pilatus%20PC-12%2F47E%20(NG)/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Pilatus%20PC-12%2F47E%20(NG)/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Pilatus%20PC-12%2F47E%20(NG)/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Pilatus%20PC-12%2F47E%20(NG)/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Pilatus%20PC-12%2F47E%20(NG)/01.jpg' WHERE name = 'Pilatus PC-12/47E (NG)';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Pilatus%20PC-24/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Pilatus%20PC-24/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Pilatus%20PC-24/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Pilatus%20PC-24/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Pilatus%20PC-24/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Pilatus%20PC-24/01.jpg' WHERE name = 'Pilatus PC-24';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Praetor%20600/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Praetor%20600/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Praetor%20600/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Praetor%20600/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Praetor%20600/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Praetor%20600/01.jpg' WHERE name = 'Praetor 600';

UPDATE aircraft SET gallery = ARRAY['https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Premier%20IA/01.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Premier%20IA/02.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Premier%20IA/03.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Premier%20IA/04.jpg','https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Premier%20IA/05.jpg'], image = 'https://cwiznhnowqjvziaghjaa.supabase.co/storage/v1/object/public/Aircraft/Premier%20IA/01.jpg' WHERE name = 'Premier IA';
